name: Setup Node.js environment
  uses: actions/setup-node@v3.6.0
name: Install Lighthouse CI
  run: |
    npm install -g @lhci/cli
name: Run Lighthouse CI
  run: |
    lhci autorun --url=https://www.diarydirectory.com
